// <auto-generated />
using System;
using HeThongDatBan_GoiMon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeThongDatBan_GoiMon.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    partial class RestaurantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.AppModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AppModules");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.BusinessHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DayOfWeek")
                        .IsUnique();

                    b.ToTable("BusinessHours");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.CustomerOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DiningSessionId")
                        .HasColumnType("int");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DiningSessionId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.DiningArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DiningAreas");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.DiningSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("GuestCount")
                        .HasColumnType("int");

                    b.Property<int?>("OpenedById")
                        .HasColumnType("int");

                    b.Property<string>("PublicSessionToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantTableId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("OpenedById");

                    b.HasIndex("PublicSessionToken")
                        .IsUnique();

                    b.HasIndex("ReservationId");

                    b.HasIndex("RestaurantTableId");

                    b.ToTable("DiningSessions");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutUntilUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PasswordChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("EmployeeAccounts");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EmployeeAccountId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeAccountId");

                    b.ToTable("FailedLoginAttempts");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Invoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CancelledById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DiningSessionId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("DiscountReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("FinalizedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("CancelledById");

                    b.HasIndex("DiningSessionId")
                        .IsUnique();

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ShiftId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.InvoiceLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsChargeableAfterCancellation")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("LineTotalAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.LoginAuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EmployeeAccountId")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("WasSuccessful")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeAccountId");

                    b.ToTable("LoginAuditLogs");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MenuCategories");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuChangeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("NewName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("NewPrice")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("OldName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("OldPrice")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuChangeLogs");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MenuCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PreparationMinutes")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MenuCategoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuItemAvailability", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("BusinessDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("MenuItemId", "BusinessDate")
                        .IsUnique();

                    b.ToTable("MenuItemAvailabilities");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RecipientAccountId")
                        .HasColumnType("int");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientAccountId");

                    b.HasIndex("ReservationId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CustomerOrderId")
                        .HasColumnType("bigint");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("MenuItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ServedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("StatusUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerOrderId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.OrderItemStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("int");

                    b.Property<long>("OrderItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemStatusHistories");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("CashReceivedAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("ChangeAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("CollectedById")
                        .HasColumnType("int");

                    b.Property<long>("InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTimeOffset>("PaidAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CollectedById");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ConfirmedById")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PartySize")
                        .HasColumnType("int");

                    b.Property<string>("ReservationCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("ReservationEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReservationStartUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("RestaurantTableId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ConfirmedById");

                    b.HasIndex("ReservationCode")
                        .IsUnique();

                    b.HasIndex("RestaurantTableId", "ReservationStartUtc");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.ReservationStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationStatusHistories");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.RestaurantTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DiningAreaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("StatusUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DiningAreaId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("RestaurantTables");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MANAGER",
                            Name = "Quản lý"
                        },
                        new
                        {
                            Id = 2,
                            Code = "WAITER",
                            Name = "Nhân viên phục vụ"
                        },
                        new
                        {
                            Id = 3,
                            Code = "KITCHEN",
                            Name = "Bếp"
                        },
                        new
                        {
                            Id = 4,
                            Code = "CASHIER",
                            Name = "Thu ngân"
                        });
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.RoleModulePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("AppModuleId")
                        .HasColumnType("int");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId", "AppModuleId");

                    b.HasIndex("AppModuleId");

                    b.ToTable("RoleModulePermissions");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CashDifferenceAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("CountedCashAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("DifferenceReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("EndedById")
                        .HasColumnType("int");

                    b.Property<decimal>("ExpectedCashAmount")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StartedById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("EndedById");

                    b.HasIndex("ShiftCode")
                        .IsUnique();

                    b.HasIndex("StartedById");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.TableMerge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("MergedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MergedById")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryDiningSessionId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryDiningSessionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UnmergedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("UnmergedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MergedById");

                    b.HasIndex("PrimaryDiningSessionId");

                    b.HasIndex("SecondaryDiningSessionId");

                    b.HasIndex("UnmergedById");

                    b.ToTable("TableMerges");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.TableStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("ChangedById")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantTableId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("RestaurantTableId");

                    b.ToTable("TableStatusHistories");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.CustomerOrder", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.DiningSession", "DiningSession")
                        .WithMany("Orders")
                        .HasForeignKey("DiningSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("DiningSession");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.DiningSession", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "OpenedBy")
                        .WithMany()
                        .HasForeignKey("OpenedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Reservation", "Reservation")
                        .WithMany("DiningSessions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.RestaurantTable", "RestaurantTable")
                        .WithMany("DiningSessions")
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OpenedBy");

                    b.Navigation("Reservation");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Role", "Role")
                        .WithMany("EmployeeAccounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.FailedLoginAttempt", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "EmployeeAccount")
                        .WithMany("FailedLoginAttempts")
                        .HasForeignKey("EmployeeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeAccount");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Invoice", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.DiningSession", "DiningSession")
                        .WithOne()
                        .HasForeignKey("HeThongDatBan_GoiMon.Models.Entities.Invoice", "DiningSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Shift", "Shift")
                        .WithMany("Invoices")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CancelledBy");

                    b.Navigation("DiningSession");

                    b.Navigation("Shift");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.InvoiceLine", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Invoice");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.LoginAuditLog", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "EmployeeAccount")
                        .WithMany("LoginAuditLogs")
                        .HasForeignKey("EmployeeAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeAccount");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuChangeLog", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.MenuItem", "MenuItem")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuItem", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.MenuCategory", "MenuCategory")
                        .WithMany("MenuItems")
                        .HasForeignKey("MenuCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuCategory");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuItemAvailability", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.MenuItem", "MenuItem")
                        .WithMany("Availabilities")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.NotificationLog", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "RecipientAccount")
                        .WithMany()
                        .HasForeignKey("RecipientAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Reservation", "Reservation")
                        .WithMany("Notifications")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RecipientAccount");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.OrderItem", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.CustomerOrder", "CustomerOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("CustomerOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.MenuItem", "MenuItem")
                        .WithMany("OrderItems")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerOrder");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.OrderItemStatusHistory", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.OrderItem", "OrderItem")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Payment", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "CollectedBy")
                        .WithMany()
                        .HasForeignKey("CollectedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectedBy");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Reservation", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "ConfirmedBy")
                        .WithMany()
                        .HasForeignKey("ConfirmedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.RestaurantTable", "RestaurantTable")
                        .WithMany("Reservations")
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ConfirmedBy");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.ReservationStatusHistory", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Reservation", "Reservation")
                        .WithMany("StatusHistory")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.RestaurantTable", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.DiningArea", "DiningArea")
                        .WithMany("RestaurantTables")
                        .HasForeignKey("DiningAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiningArea");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.RoleModulePermission", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.AppModule", "AppModule")
                        .WithMany("Permissions")
                        .HasForeignKey("AppModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppModule");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Shift", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "EndedBy")
                        .WithMany()
                        .HasForeignKey("EndedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "StartedBy")
                        .WithMany()
                        .HasForeignKey("StartedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EndedBy");

                    b.Navigation("StartedBy");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.TableMerge", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "MergedBy")
                        .WithMany()
                        .HasForeignKey("MergedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.DiningSession", "PrimaryDiningSession")
                        .WithMany()
                        .HasForeignKey("PrimaryDiningSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.DiningSession", "SecondaryDiningSession")
                        .WithMany()
                        .HasForeignKey("SecondaryDiningSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "UnmergedBy")
                        .WithMany()
                        .HasForeignKey("UnmergedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MergedBy");

                    b.Navigation("PrimaryDiningSession");

                    b.Navigation("SecondaryDiningSession");

                    b.Navigation("UnmergedBy");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.TableStatusHistory", b =>
                {
                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HeThongDatBan_GoiMon.Models.Entities.RestaurantTable", "RestaurantTable")
                        .WithMany("StatusHistory")
                        .HasForeignKey("RestaurantTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("RestaurantTable");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.AppModule", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.CustomerOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.DiningArea", b =>
                {
                    b.Navigation("RestaurantTables");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.DiningSession", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.EmployeeAccount", b =>
                {
                    b.Navigation("FailedLoginAttempts");

                    b.Navigation("LoginAuditLogs");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Invoice", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuCategory", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.MenuItem", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("ChangeLogs");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.OrderItem", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Reservation", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("Notifications");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.RestaurantTable", b =>
                {
                    b.Navigation("DiningSessions");

                    b.Navigation("Reservations");

                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Role", b =>
                {
                    b.Navigation("EmployeeAccounts");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("HeThongDatBan_GoiMon.Models.Entities.Shift", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
